/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jobs
         * @description List jobs ordered by ``created_at`` DESC.
         *
         *     Optional ``?status=`` filter, ``?limit=`` (silently capped at
         *     :data:`LIST_LIMIT_CAP`), and ``?offset=`` for pagination.
         */
        get: operations["get_jobs_jobs_get"];
        put?: never;
        /**
         * Post Job
         * @description Create a new job, or collapse a duplicate ``Idempotency-Key`` to the existing job.
         *
         *     Plan 04-03 (SC-5, D-07, Fix 7):
         *
         *     - No ``Idempotency-Key`` header -> create a new job (201, existing
         *       behavior).
         *     - Valid ``Idempotency-Key`` + first call -> reserve the key +
         *       create a new job under the reserved id (201).
         *     - Valid ``Idempotency-Key`` + duplicate call -> the key INSERT
         *       collides (IntegrityError); the handler re-reads the existing job
         *       and returns it (200, NOT 201) with no orphan duplicate (Fix 7 --
         *       Codex HIGH).
         *     - Invalid / oversized ``Idempotency-Key`` -> 422 BEFORE any DB
         *       write (T-04-01, Codex MEDIUM -- exact exception path).
         *
         *     The status code is set per-response via the ``Response`` dependency
         *     (201 for new, 200 for duplicate); the route's declared 201 is the
         *     default for the no-key + first-key paths.
         */
        post: operations["post_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Source
         * @description Stream the raw request body to ``data/jobs/<id>/source.<ext>`` (D-11, SC-1).
         *
         *     Phase 5 streaming upload endpoint (the "other half" of Phase 4 D-04's
         *     generalized ``ingested`` check -- the browser cannot supply a
         *     server-side ``source_path``, so this route writes the file directly).
         *
         *     Flow (per RESEARCH Pattern 1 + Pitfall 1/2/3):
         *
         *     1. Validate the extension BEFORE writing (T-05-01 -- path traversal
         *        reject + allowlist enforced by :func:`validate_source_ext`).
         *     2. Resolve idempotency + create the job in ``status='uploading'`` via
         *        the existing :func:`resolve_or_create` flow, passing
         *        :func:`create_upload_job` as the factory (Phase 4 D-07 reuse).
         *     3. Stream the raw body via ``request.stream()`` (the true streaming
         *        path -- NOT the SpooledTemporaryFile-backed file-upload helper,
         *        per Pitfall 2 / FastAPI issue #3136) to ``.tmp_<source.<ext>>``
         *        with ``aiofiles``, ``fsync``, then atomic ``os.replace`` (T-05-02)
         *        wrapped in :func:`retry_windows` for transient Windows
         *        AV/Search Indexer locks.
         *     4. On any failure (client disconnect, disk error) the
         *        ``except BaseException`` branch ``os.unlink``s the temp file so
         *        no partial ``source.<ext>`` is left on disk.
         *     5. Patch ``manifest.source_path`` + ``source_type='local'`` directly
         *        (Pitfall 3 -- do NOT call ``update_stage("ingested")``; that sets
         *        ``status='ingesting'`` which blocks the widened ``enqueue`` clause).
         *     6. :func:`enqueue` flips ``status='queued'`` (Task 1 widened the
         *        clause to accept ``'uploading'``) and wakes the worker. The
         *        orchestrator's generalized ``ingested`` check sees the
         *        in-job-dir ``source.<ext>`` and skips the ingest stage.
         *
         *     Returns 201 + :class:`JobResponse` for a new job, or 200 + the
         *     existing job on a duplicate ``Idempotency-Key`` (Phase 4 D-07).
         */
        post: operations["upload_source_jobs_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transcript
         * @description Return the parsed :class:`Transcript` for ``job_id`` (D-14).
         *
         *     Serves the on-disk ``transcript.json`` (Phase 3 schema) so the FE
         *     detail view can render it. Returns:
         *
         *     - 200 + the :class:`Transcript` JSON when ``transcript.json`` exists.
         *     - 404 ``{"detail": "transcript not found"}`` when the job has no
         *       transcript yet (still queued / transcribing -- the FE shows a
         *       "Transcribing..." state).
         *     - 400 ``{"detail": "invalid job id"}`` for a malformed id.
         */
        get: operations["get_transcript_jobs__job_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job By Id
         * @description Return one job by id, or 404 with ``{"detail": "job not found"}``.
         */
        get: operations["get_job_by_id_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Cancel
         * @description Cancel a job via the cooperative ``queue.cancel`` path (WR-04, D-06).
         *
         *     The route calls ``queue.cancel(job_id, session, settings)`` -- the
         *     cooperative cancel implemented in plan 04-02 -- and maps the returned
         *     ``{status, id}`` dict to a :class:`JobResponse`:
         *
         *     - ``{}`` (job not found) -> 404.
         *     - ``queued``: ``queue.cancel`` runs ``cancel_job`` (DB-first + rmtree) +
         *       ``_work_signal.set``; the route returns 200 with the cancelled row.
         *     - ``running`` (starting / ingesting / transcribing): ``queue.cancel`` only
         *       sets the ``_running`` threading.Event cancel flag; the orchestrator's
         *       ``JobCancelled`` path does the ``cancel_job`` + rmtree at the next chunk
         *       boundary (no destructive out-from-under rmtree -- WR-04). The route
         *       returns 200 with the current row (still ``transcribing`` at the moment
         *       of return -- the orchestrator flips it asynchronously).
         *     - ``terminal`` (done / failed / cancelled): ``queue.cancel`` is a no-op
         *       returning the row unchanged (D-06 idempotent); the route returns 200
         *       with the row (NOT 404 -- a second cancel is a no-op).
         *
         *     Returns 400 if the job id is not a valid UUID.
         */
        post: operations["post_cancel_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Stage
         * @description Advance the job's stage and optionally patch the manifest.
         *
         *     - 400 if the job id is not a valid UUID.
         *     - 404 if the job's manifest does not exist on disk.
         *     - 422 if the :class:`ManifestPatch` is invalid (extra fields
         *       or wrong types).
         *     - 200 with the new :class:`JobManifest` on success.
         */
        post: operations["post_stage_jobs__job_id__stage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/stale-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Stale Check
         * @description Mark a job failed with ``error='stalled'`` if it is stale.
         *
         *     Returns 404 if the job does not exist; 200 with
         *     ``{stale, marked}`` on success. The lookup happens BEFORE
         *     the UUID is validated so a non-UUID id like ``missing-id``
         *     still returns 404 (consistent with ``GET /jobs/{id}``).
         */
        post: operations["post_stale_check_jobs__job_id__stale_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return the current :class:`Settings` (lax output).
         *
         *     D-05: ``hf_token`` is NEVER returned in the response regardless of
         *     ``?reveal=``. The on-disk file holds the base64-encoded value; the
         *     response nulls it so a stray ``GET /settings`` does not leak the
         *     token to a caller reading the body. We build the response body
         *     from ``current().model_dump()`` and explicitly null ``hf_token``
         *     before returning; ``response_model=Settings`` re-validates the
         *     dict (the ``hf_token`` field_validator passes ``None`` through, and
         *     the field_serializer returns ``None`` for ``None``), so the wire
         *     body carries ``"hf_token": null``.
         */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Settings
         * @description Apply a PATCH to the settings; emit ``X-Restart-Required: true``
         *     on the response when ``data_dir`` actually changed.
         *
         *     The response body is the in-memory state AFTER the PATCH:
         *
         *     - When ``data_dir`` changes (restart-required), the in-memory
         *       state is unchanged (Plan 01-04 H1: defer the swap to restart).
         *       The body is the BOOT value of ``data_dir``; the new value is
         *       durable on disk under the ``pending`` key.
         *     - When no restart is required (omitted ``data_dir`` or same
         *       value), the body is the new in-memory state (which equals the
         *       patched value).
         */
        patch: operations["patch_settings_settings_patch"];
        trace?: never;
    };
    "/diagnostics/gpu-burn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gpu Burn
         * @description Re-run the two-stage detect + burn test and persist the result.
         *
         *     Hot-swap (H1): the in-memory ``Settings.backend`` /
         *     ``Settings.backend_probe`` are swapped immediately and the on-disk
         *     ``settings.json`` is rewritten atomically (D-04 Phase-1 helper).
         *     No ``X-Restart-Required`` header (only ``data_dir`` is
         *     restart-required).
         */
        post: operations["gpu_burn_diagnostics_gpu_burn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/vram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Vram
         * @description Return the current VRAM state for the active backend.
         */
        get: operations["get_vram_diagnostics_vram_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/test-hf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Hf Token
         * @description Probe the configured HF token against the gated pyannote repo.
         *
         *     Four-state contract (D-05, Pitfall 3):
         *
         *     - ``skipped`` -> 200 (no token, OR HF Hub unreachable / network error)
         *     - ``ok`` -> 200 (token valid + gated terms accepted; ``user`` set)
         *     - ``rejected`` with ``reason="token invalid"`` -> 401
         *     - ``rejected`` with ``reason="model terms not accepted"`` -> 403
         *
         *     The helper :func:`validate_token` never raises; the route maps the
         *     typed result to the HTTP code.
         */
        post: operations["test_hf_token_diagnostics_test_hf_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description Return the installed + available + active model set.
         */
        get: operations["list_models_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download Model
         * @description Kick off an async download for ``id`` (D-01 on-demand).
         *
         *     Deduplicates in-flight downloads: if a task for ``id`` is already
         *     ``queued`` or ``running``, returns 409 instead of overwriting the
         *     progress entry and spawning a racing second background task.
         */
        post: operations["download_model_models__id__download_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Status
         * @description Return the current :class:`DownloadProgress` for ``id``.
         */
        get: operations["download_status_models__id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/download-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Progress Sse
         * @description SSE stream of :class:`DownloadProgress` for ``id`` (Phase 5 consumer).
         */
        get: operations["download_progress_sse_models__id__download_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Model
         * @description Load ``id`` into VRAM (D-04 concurrent policy + SC-4 budget gate).
         */
        post: operations["load_model_models__id__load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unload Model
         * @description Unload ``id`` from VRAM (D-03 idempotent, 204 No Content).
         */
        post: operations["unload_model_models__id__unload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BackendProbe
         * @description Result of a real-kernel burn test on the active backend.
         *
         *     ``device_name`` is the GPU marketing name (``"NVIDIA RTX 2000 Ada"``,
         *     ``"AMD Radeon RX 6800 XT"``) or ``"CPU"`` on the silent fallback
         *     path (D-06). ``vram_total_mb`` and ``burn_test_ms`` are ``None`` on
         *     CPU: the CPU path has no VRAM and no kernel to time. ``probed_at``
         *     is the ISO-8601 UTC timestamp of the probe (D-06 log-only verdict
         *     that Phase 10 surfaces).
         */
        BackendProbe: {
            backend: components["schemas"]["GpuBackend"];
            /** Device Name */
            device_name: string;
            /** Driver Version */
            driver_version?: string | null;
            /** Vram Total Mb */
            vram_total_mb?: number | null;
            /** Burn Test Ms */
            burn_test_ms?: number | null;
            /** Probed At */
            probed_at?: string;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * CreateJobRequest
         * @description Payload for ``POST /jobs``.
         *
         *     Strict input: any extra keys or wrong types are rejected at the API
         *     boundary. This catches front-end bugs early (PITFALLS pitfall 7).
         */
        CreateJobRequest: {
            /** Source Type */
            source_type?: string | null;
            /** Source Path */
            source_path?: string | null;
        };
        /**
         * DownloadProgress
         * @description Progress of an async download (read by the status + SSE routes).
         */
        DownloadProgress: {
            /** Model Id */
            model_id: string;
            /**
             * Bytes Done
             * @default 0
             */
            bytes_done: number;
            /** Bytes Total */
            bytes_total?: number | null;
            /**
             * State
             * @default queued
             * @enum {string}
             */
            state: "queued" | "running" | "verifying" | "done" | "failed" | "resuming";
            /** Message */
            message?: string | null;
        };
        /**
         * DownloadTaskResponse
         * @description Response of ``POST /models/{id}/download`` (202 Accepted).
         */
        DownloadTaskResponse: {
            /** Task Id */
            task_id: string;
            /** Status Url */
            status_url: string;
        };
        /**
         * GpuBackend
         * @description Active GPU backend detected on this machine.
         *
         *     Values are lowercase short strings so the on-disk ``settings.json``
         *     reads cleanly (``"backend": "cuda"``) and the OpenAPI enum surfaces
         *     the same tokens the React settings panel will display.
         * @enum {string}
         */
        GpuBackend: "cuda" | "rocm" | "cpu" | "directml" | "vulkan";
        /**
         * GpuBurnResult
         * @description Response of ``POST /diagnostics/gpu-burn`` (the re-detect path).
         */
        GpuBurnResult: {
            probe: components["schemas"]["BackendProbe"];
            active_backend: components["schemas"]["GpuBackend"];
            /** Settings Written */
            settings_written: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HfTokenResult
         * @description Four-state result of ``POST /diagnostics/test-hf-token`` (D-05, Pitfall 3).
         *
         *     - ``skipped``: no token configured, or HF Hub unreachable (network
         *       error never blocks the app — Pitfall 3).
         *     - ``ok``: the token authenticated against HF Hub; ``user`` carries
         *       the HF username (from the ``x-repo-author`` response header).
         *     - ``rejected``: the token is invalid (401) or the gated pyannote
         *       repo's terms have not been accepted (403); ``reason`` + ``fix``
         *       carry the user-facing explanation.
         */
        HfTokenResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "skipped" | "ok" | "rejected";
            /** Reason */
            reason?: string | null;
            /** User */
            user?: string | null;
            /** Fix */
            fix?: string | null;
        };
        /**
         * JobManifest
         * @description File-on-disk job manifest, written atomically by every stage mutator.
         *
         *     The manifest is the rich "one read = full picture" snapshot of a job
         *     (D-05). It is always kept consistent with the per-job folder contents.
         *     Lax for output: deserialising existing files should never fail because
         *     of an unknown future field.
         *
         *     Plan 01-03 adds ``diarization_enabled`` (default ``False`` - diarization
         *     is opt-in per D-11; the settings panel in Phase 7 flips it to True).
         *     The default keeps existing manifest JSON files from breaking (the
         *     field is missing, Pydantic fills in the default).
         */
        JobManifest: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Job Id */
            job_id: string;
            /** Source Type */
            source_type?: string | null;
            /** Source Path */
            source_path?: string | null;
            /** Source Sha256 */
            source_sha256?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Language */
            language?: string | null;
            /** Summary Kinds */
            summary_kinds?: string[];
            /**
             * Diarization Enabled
             * @default false
             */
            diarization_enabled: boolean;
            /**
             * Status
             * @default queued
             */
            status: string;
            /** Current Stage */
            current_stage?: string | null;
            stage_timestamps: components["schemas"]["StageTimestamps"];
            /** Error */
            error?: string | null;
        };
        /**
         * JobResponse
         * @description Response payload for job endpoints.
         *
         *     Strict output for the API boundary; the ``id`` is a UUIDv4 string and
         *     ``created_at`` is a timezone-aware UTC ``datetime`` (the
         *     ``+00:00`` offset is preserved on the wire as a real suffix, not
         *     the ``Z`` shorthand, so the timestamp is unambiguously parseable
         *     by strict ISO 8601 consumers).
         *
         *     Fields added in Plan 01-02 (``source_sha256``, ``duration_s``,
         *     ``language``, ``summary_kinds``, ``updated_at``, ``error``) are
         *     all optional and default to None / empty list so existing code
         *     paths and tests that construct a minimal response keep working.
         */
        JobResponse: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "uploading" | "starting" | "ingesting" | "transcribing" | "diarizing" | "summarizing" | "done" | "failed" | "cancelled";
            /** Created At */
            created_at: string;
            /** Source Type */
            source_type?: string | null;
            /** Source Path */
            source_path?: string | null;
            /** Source Sha256 */
            source_sha256?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Language */
            language?: string | null;
            /** Summary Kinds */
            summary_kinds?: string[];
            /** Updated At */
            updated_at?: string | null;
            /** Error */
            error?: string | null;
        };
        /**
         * LoadedModel
         * @description One model currently resident in VRAM (the load() return value).
         */
        LoadedModel: {
            category: components["schemas"]["ModelCategory"];
            /** Model Id */
            model_id: string;
            spec: components["schemas"]["ModelSpec"];
            /** Vram Bytes */
            vram_bytes: number;
            /** Loaded At */
            loaded_at: string;
        };
        /**
         * LoadedModelInfo
         * @description One entry in :class:`VRAMState.loaded` (02-02 plumbs the real values).
         */
        LoadedModelInfo: {
            category: components["schemas"]["ModelCategory"];
            /** Model Id */
            model_id: string;
            /** Vram Mb */
            vram_mb: number;
            /** Loaded At */
            loaded_at: string;
        };
        /**
         * ManifestPatch
         * @description Allowlisted, strict patch for the on-disk manifest.
         *
         *     The plan truth statement (Codex HIGH #7): the patch ONLY forwards
         *     the user-mutable fields. The protected fields
         *     (``current_stage``, ``job_id``, ``schema_version``,
         *     ``stage_timestamps``, ``status``, ``error``) are owned by the
         *     helper that applies the patch (:func:`app.jobs.manifest.update_stage`)
         *     and CANNOT be set via this model.
         *
         *     - ``strict=True`` rejects wrong types (``source_type: 123`` -> 422).
         *     - ``extra="forbid"`` rejects unknown keys (``unknown_field: x`` -> 422)
         *       and also catches the protected fields (they are not on this
         *       model, so they are extras).
         */
        ManifestPatch: {
            /** Source Type */
            source_type?: string | null;
            /** Source Path */
            source_path?: string | null;
            /** Source Sha256 */
            source_sha256?: string | null;
            /** Duration S */
            duration_s?: number | null;
            /** Language */
            language?: string | null;
            /** Summary Kinds */
            summary_kinds?: string[] | null;
        };
        /**
         * ModelCategory
         * @description Per-category model slot used by the model manager (02-02).
         * @enum {string}
         */
        ModelCategory: "stt" | "diarize" | "llm";
        /**
         * ModelSet
         * @description Per-category model set selected by a :class:`QualityPreset`.
         */
        ModelSet: {
            stt: components["schemas"]["ModelSpec"];
            diarize: components["schemas"]["ModelSpec"];
            llm: components["schemas"]["ModelSpec"];
        };
        /**
         * ModelSpec
         * @description One model slot in a :class:`ModelSet` (values filled in 02-02).
         */
        ModelSpec: {
            /** Repo Id */
            repo_id: string;
            /** File */
            file?: string | null;
            /** Revision */
            revision?: string | null;
            /** Expected Size Bytes */
            expected_size_bytes?: number | null;
            /** Expected Sha256 */
            expected_sha256?: string | null;
        };
        /**
         * ModelsListResponse
         * @description Response of ``GET /models`` (installed + available + active_set).
         */
        ModelsListResponse: {
            /** Installed */
            installed: components["schemas"]["ModelSpec"][];
            /** Available */
            available: {
                [key: string]: unknown;
            }[];
            active_set: components["schemas"]["ModelSet"];
        };
        /**
         * QualityPreset
         * @description Model-set preset (D-09). Values filled by 02-02's ``presets.py``.
         * @enum {string}
         */
        QualityPreset: "small" | "balanced" | "large";
        /**
         * Settings
         * @description Persisted application settings (D-14: model is source of truth).
         *
         *     Phase 2 extends the Phase 1 ``data_dir``-only model with seven new
         *     fields per D-08 (declare-now): ``backend``, ``backend_probe``,
         *     ``hf_token``, ``quality_preset``, ``per_category_overrides``,
         *     ``concurrent_models``, ``vram_budget_fraction``. A fresh boot
         *     writes a single stable on-disk format carrying every field the
         *     model manager (02-02) and the Phase 10 settings panel will read.
         *
         *     ``backend`` has NO default: it is set by the first-run detect path
         *     (``app.main`` lifespan) and by ``POST /diagnostics/gpu-burn`` only.
         *     The other six new fields have defaults so the detect path can
         *     construct a ``Settings`` with just ``data_dir`` + ``backend`` +
         *     ``backend_probe``.
         *
         *     ``hf_token`` is base64-encoded on the on-disk dump via
         *     :func:`_serialize_hf_token` and base64-decoded on load via
         *     :func:`_decode_hf_token` (D-05 — no accidental cleartext on
         *     ``cat settings.json``). The ``GET /settings`` response NULLS the
         *     field regardless of the on-disk value (handled in the route layer
         *     so the model itself stays the single source of truth for the
         *     on-disk format).
         */
        Settings: {
            /** Data Dir */
            data_dir: string;
            backend: components["schemas"]["GpuBackend"];
            backend_probe?: components["schemas"]["BackendProbe"] | null;
            /** Hf Token */
            hf_token?: string | null;
            /** @default balanced */
            quality_preset: components["schemas"]["QualityPreset"];
            per_category_overrides?: components["schemas"]["ModelSet"] | null;
            /**
             * Concurrent Models
             * @default false
             */
            concurrent_models: boolean;
            /**
             * Vram Budget Fraction
             * @default 0.85
             */
            vram_budget_fraction: number;
            /**
             * Run Worker
             * @default true
             */
            run_worker: boolean;
            /**
             * Ws Subscriber Cap
             * @default 16
             */
            ws_subscriber_cap: number;
            /**
             * Idempotency Ttl Hours
             * @default 24
             */
            idempotency_ttl_hours: number;
        };
        /**
         * StageTimestamps
         * @description Wall-clock timestamps for each pipeline stage that a job can reach.
         *
         *     All values are ISO 8601 strings produced by :func:`app.util.time.utcnow_iso`
         *     (always terminating in ``+00:00``). A ``None`` value means the stage has
         *     not been reached yet.
         */
        StageTimestamps: {
            /** Queued */
            queued: string;
            /** Ingested */
            ingested?: string | null;
            /** Transcribed */
            transcribed?: string | null;
            /** Diarized */
            diarized?: string | null;
            /** Summarized */
            summarized?: string | null;
            /** Done */
            done?: string | null;
        };
        /**
         * StageUpdateRequest
         * @description Payload for ``POST /jobs/{id}/stage``.
         *
         *     Strict input; ``stage`` is the new value for ``manifest.current_stage``,
         *     and ``manifest_patch`` (optional) carries the user-mutable fields the
         *     caller wants to change at the same time.
         */
        StageUpdateRequest: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "ingested" | "transcribed" | "diarized" | "summarized" | "done";
            manifest_patch?: components["schemas"]["ManifestPatch"] | null;
        };
        /**
         * StaleCheckRequest
         * @description Payload for ``POST /jobs/{id}/stale-check``.
         */
        StaleCheckRequest: {
            /**
             * Threshold S
             * @default 600
             */
            threshold_s: number;
        };
        /**
         * StaleCheckResponse
         * @description Response for ``POST /jobs/{id}/stale-check``.
         */
        StaleCheckResponse: {
            /** Stale */
            stale: boolean;
            /** Marked */
            marked: boolean;
        };
        /**
         * Transcript
         * @description The full transcript for a single job.
         *
         *     The list of ``segments`` is the canonical payload; the rest of the
         *     fields are metadata that downstream stages or the UI may want
         *     without re-parsing the segment list.
         */
        Transcript: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Job Id */
            job_id: string;
            /** Language */
            language?: string | null;
            /** Segments */
            segments?: components["schemas"]["TranscriptSegment"][];
        };
        /**
         * TranscriptSegment
         * @description A single timed chunk of the transcript.
         *
         *     ``speaker`` and ``confidence`` are optional because the STT stage
         *     (Phase 3) may not know the speaker at transcription time (that is
         *     filled in by the diarization stage, Phase 7) and not every STT
         *     backend emits a per-segment confidence score.
         */
        TranscriptSegment: {
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Text */
            text: string;
            /** Speaker */
            speaker?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * UpdateSettingsRequest
         * @description Strict input model for ``PATCH /settings`` (D-15 strict input).
         *
         *     Phase 2 extends the Phase 1 ``data_dir``-only request with five
         *     new optional fields (``hf_token``, ``quality_preset``,
         *     ``per_category_overrides``, ``concurrent_models``,
         *     ``vram_budget_fraction``). All fields are optional (``| None =
         *     None``) so a PATCH can hot-swap any single field without sending
         *     the others (H1: only ``data_dir`` is restart-required; the new
         *     fields are hot-swap).
         *
         *     ``backend`` and ``backend_probe`` are NOT declared (D-08 — only
         *     the detect/burn path writes them). ``extra="forbid"`` rejects them
         *     at the API boundary with 422.
         *
         *     A PATCH with NO fields set (empty body ``{}``) is rejected with
         *     422 — a no-op PATCH is invalid. This preserves the Phase 1
         *     ``test_empty_patch_returns_422`` contract while allowing single-
         *     field hot-swaps.
         *
         *     The ``data_dir`` validator runs ONLY when ``data_dir`` is in the
         *     request (``model_fields_set``); a PATCH that omits ``data_dir``
         *     does not trigger path validation. An explicit ``null`` for
         *     ``data_dir`` is rejected (preserves ``test_data_dir_null_returns_422``).
         */
        UpdateSettingsRequest: {
            /** Data Dir */
            data_dir?: string | null;
            /** Hf Token */
            hf_token?: string | null;
            quality_preset?: components["schemas"]["QualityPreset"] | null;
            per_category_overrides?: components["schemas"]["ModelSet"] | null;
            /** Concurrent Models */
            concurrent_models?: boolean | null;
            /** Vram Budget Fraction */
            vram_budget_fraction?: number | null;
        };
        /**
         * VRAMState
         * @description Snapshot of GPU/CPU memory state returned by ``GET /diagnostics/vram``.
         *
         *     ``loaded`` is empty until 02-02's model manager wires in
         *     (``ManagerState.live_vram_bytes`` is the source for this list).
         */
        VRAMState: {
            backend: components["schemas"]["GpuBackend"];
            /** Total Mb */
            total_mb: number;
            /** Available Mb */
            available_mb: number;
            /** Used Mb */
            used_mb: number;
            /** Loaded */
            loaded?: components["schemas"]["LoadedModelInfo"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Summary
         * @description The full output of one summary template for a single job.
         *
         *     ``sections`` is keyed by section name (e.g. ``"action_items"``,
         *     ``"key_takeaways"``) and the value is the rendered text. The exact
         *     section names are template-specific; downstream code that needs
         *     the shape should branch on ``kind``.
         */
        Summary: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            /** Job Id */
            job_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "meeting" | "investment" | "concept" | "quick_recap";
            /** Created At */
            created_at: string;
            /** Sections */
            sections?: {
                [key: string]: string;
            };
            /**
             * Model
             * @default null
             */
            model: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_jobs_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_job_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_jobs_upload_post: {
        parameters: {
            query?: never;
            header: {
                "X-Filename": string;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_jobs__job_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transcript"];
                };
            };
            /** @description transcript not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_by_id_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cancel_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_stage_jobs__job_id__stage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobManifest"];
                };
            };
            /** @description job or manifest not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description ManifestPatch validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_stale_check_jobs__job_id__stale_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaleCheckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaleCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    patch_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gpu_burn_diagnostics_gpu_burn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GpuBurnResult"];
                };
            };
        };
    };
    get_vram_diagnostics_vram_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VRAMState"];
                };
            };
        };
    };
    test_hf_token_diagnostics_test_hf_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HfTokenResult"];
                };
            };
        };
    };
    list_models_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsListResponse"];
                };
            };
        };
    };
    download_model_models__id__download_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_status_models__id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_progress_sse_models__id__download_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_model_models__id__load_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoadedModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unload_model_models__id__unload_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
